# Dependencies
markdown: redcarpet
pygments: true

redcarpet:
  extensions: ["with_toc_data", "tables"]

# Permalinks
permalink: "/blog/:year/:month/:day/:title"

# Server
destination:      ./_gh_pages
exclude:          [".gitignore", "README.md", "stylesheets/less"]
port:             9001
