# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink: "/blog/:year/:month/:day/:title"

# Server
destination:      ./_gh_pages
exclude:          [".gitignore", "README.md", "stylesheets/less"]
port:             9001
